---
- name: Demo playbook to test callback plugin - Remove
  hosts: msnyder-vm1.nsls2.bnl.local
  tasks:

    - name: Stop and disable httpd service
      ansible.builtin.service:
        name: httpd
        enabled: false
        state: stopped

    - name: Remove httpd package
      ansible.builtin.dnf:
        name: httpd
        state: absent
      when: ansible_webserver_remove_httpd is true
